/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tiger.example;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class studentConstants {

  public static final byte SHORT_VALUE_1 = (byte)100;

  public static final byte SHORT_VALUE_2 = (byte)-2;

  public static final double DOUBLE_VALUE_1 = 3.1400000000000001;

  public static final double DOUBLE_VALUE_2 = 0.0000120000000000;

  public static final double DOUBLE_VALUE_3 = 350000000.0000000000000000;

  public static final java.util.List<java.lang.String> LIST_VALUE = new java.util.ArrayList<java.lang.String>();
  static {
    LIST_VALUE.add("tom");
    LIST_VALUE.add("joney");
    LIST_VALUE.add("catiy");
  }

  public static final java.util.Map<java.lang.String,java.lang.String> MAP_VALUE = new java.util.HashMap<java.lang.String,java.lang.String>();
  static {
    MAP_VALUE.put("age", "20");
    MAP_VALUE.put("name", "johnson");
  }

}
