// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: classroom.proto
// Protobuf Java Version: 4.29.0-rc1

package com.tiger.grpc.proto;

public final class ClassroomProto {
  private ClassroomProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "-rc1",
      ClassroomProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClassroomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.tiger.rpc.Classroom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    java.util.List<package2.StudentProto.Student> 
        getStudentsList();
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    package2.StudentProto.Student getStudents(int index);
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    int getStudentsCount();
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    java.util.List<? extends package2.StudentProto.StudentOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    package2.StudentProto.StudentOrBuilder getStudentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.tiger.rpc.Classroom}
   */
  public static final class Classroom extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.tiger.rpc.Classroom)
      ClassroomOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        Classroom.class.getName());
    }
    // Use Classroom.newBuilder() to construct.
    private Classroom(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Classroom() {
      students_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tiger.grpc.proto.ClassroomProto.internal_static_com_tiger_rpc_Classroom_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tiger.grpc.proto.ClassroomProto.internal_static_com_tiger_rpc_Classroom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tiger.grpc.proto.ClassroomProto.Classroom.class, com.tiger.grpc.proto.ClassroomProto.Classroom.Builder.class);
    }

    public static final int STUDENTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<package2.StudentProto.Student> students_;
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    @java.lang.Override
    public java.util.List<package2.StudentProto.Student> getStudentsList() {
      return students_;
    }
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends package2.StudentProto.StudentOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    @java.lang.Override
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    @java.lang.Override
    public package2.StudentProto.Student getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <code>repeated .package1.Student students = 1;</code>
     */
    @java.lang.Override
    public package2.StudentProto.StudentOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(1, students_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, students_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.tiger.grpc.proto.ClassroomProto.Classroom)) {
        return super.equals(obj);
      }
      com.tiger.grpc.proto.ClassroomProto.Classroom other = (com.tiger.grpc.proto.ClassroomProto.Classroom) obj;

      if (!getStudentsList()
          .equals(other.getStudentsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStudentsCount() > 0) {
        hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
        hash = (53 * hash) + getStudentsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.tiger.grpc.proto.ClassroomProto.Classroom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tiger.grpc.proto.ClassroomProto.Classroom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tiger.rpc.Classroom}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.tiger.rpc.Classroom)
        com.tiger.grpc.proto.ClassroomProto.ClassroomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tiger.grpc.proto.ClassroomProto.internal_static_com_tiger_rpc_Classroom_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tiger.grpc.proto.ClassroomProto.internal_static_com_tiger_rpc_Classroom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tiger.grpc.proto.ClassroomProto.Classroom.class, com.tiger.grpc.proto.ClassroomProto.Classroom.Builder.class);
      }

      // Construct using com.tiger.grpc.proto.ClassroomProto.Classroom.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
        } else {
          students_ = null;
          studentsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tiger.grpc.proto.ClassroomProto.internal_static_com_tiger_rpc_Classroom_descriptor;
      }

      @java.lang.Override
      public com.tiger.grpc.proto.ClassroomProto.Classroom getDefaultInstanceForType() {
        return com.tiger.grpc.proto.ClassroomProto.Classroom.getDefaultInstance();
      }

      @java.lang.Override
      public com.tiger.grpc.proto.ClassroomProto.Classroom build() {
        com.tiger.grpc.proto.ClassroomProto.Classroom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.tiger.grpc.proto.ClassroomProto.Classroom buildPartial() {
        com.tiger.grpc.proto.ClassroomProto.Classroom result = new com.tiger.grpc.proto.ClassroomProto.Classroom(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.tiger.grpc.proto.ClassroomProto.Classroom result) {
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
      }

      private void buildPartial0(com.tiger.grpc.proto.ClassroomProto.Classroom result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tiger.grpc.proto.ClassroomProto.Classroom) {
          return mergeFrom((com.tiger.grpc.proto.ClassroomProto.Classroom)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tiger.grpc.proto.ClassroomProto.Classroom other) {
        if (other == com.tiger.grpc.proto.ClassroomProto.Classroom.getDefaultInstance()) return this;
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                package2.StudentProto.Student m =
                    input.readMessage(
                        package2.StudentProto.Student.parser(),
                        extensionRegistry);
                if (studentsBuilder_ == null) {
                  ensureStudentsIsMutable();
                  students_.add(m);
                } else {
                  studentsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<package2.StudentProto.Student> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          students_ = new java.util.ArrayList<package2.StudentProto.Student>(students_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          package2.StudentProto.Student, package2.StudentProto.Student.Builder, package2.StudentProto.StudentOrBuilder> studentsBuilder_;

      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public java.util.List<package2.StudentProto.Student> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public package2.StudentProto.Student getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder setStudents(
          int index, package2.StudentProto.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder setStudents(
          int index, package2.StudentProto.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder addStudents(package2.StudentProto.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder addStudents(
          int index, package2.StudentProto.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder addStudents(
          package2.StudentProto.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder addStudents(
          int index, package2.StudentProto.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends package2.StudentProto.Student> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public package2.StudentProto.Student.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public package2.StudentProto.StudentOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public java.util.List<? extends package2.StudentProto.StudentOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public package2.StudentProto.Student.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            package2.StudentProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public package2.StudentProto.Student.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, package2.StudentProto.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .package1.Student students = 1;</code>
       */
      public java.util.List<package2.StudentProto.Student.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          package2.StudentProto.Student, package2.StudentProto.Student.Builder, package2.StudentProto.StudentOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              package2.StudentProto.Student, package2.StudentProto.Student.Builder, package2.StudentProto.StudentOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.tiger.rpc.Classroom)
    }

    // @@protoc_insertion_point(class_scope:com.tiger.rpc.Classroom)
    private static final com.tiger.grpc.proto.ClassroomProto.Classroom DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tiger.grpc.proto.ClassroomProto.Classroom();
    }

    public static com.tiger.grpc.proto.ClassroomProto.Classroom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Classroom>
        PARSER = new com.google.protobuf.AbstractParser<Classroom>() {
      @java.lang.Override
      public Classroom parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Classroom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Classroom> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.tiger.grpc.proto.ClassroomProto.Classroom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tiger_rpc_Classroom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tiger_rpc_Classroom_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017classroom.proto\022\rcom.tiger.rpc\032\rstuden" +
      "t.proto\"0\n\tClassroom\022#\n\010students\030\001 \003(\0132\021" +
      ".package1.StudentB(\n\024com.tiger.grpc.prot" +
      "oB\016ClassroomProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          package2.StudentProto.getDescriptor(),
        });
    internal_static_com_tiger_rpc_Classroom_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_tiger_rpc_Classroom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_tiger_rpc_Classroom_descriptor,
        new java.lang.String[] { "Students", });
    descriptor.resolveAllFeaturesImmutable();
    package2.StudentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
