my:
  simpleProp: simpleValue
  arrayProp: 1, 2, 3, 4, 5, 6, 7
  arrayProp1:
    - 127
    - 2181
  list:
    - name: abcd
      value: 1234
    - name: skdfjsk
      value: sfkds

  map:
    key1: value1
    key2: value2

spring:
  profiles:
    include: dev, test
    active: prod

---
bb: 111
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: prod
bb: 222

---
spring:
  config:
    activate:
      on-profile: fat
bb: 333

###