#my:
#  str: simpleValue
#  array: 1, 2, 3, 4, 5, 6, 7
#  list:
#    - 127
#    - 2181
#  listMap:
#    - name: abcd
#      value: 1234
#    - name: skdfjsk
#      value: sfkds
#  map:
#    key1: ${my.str}
#    key2: value2
#
#people:
#  address: &address
#    city: beijin
#  name: &name zhangsan
#
#people1:
#  address:
#    <<: *address
#  name: *name



spring:
  config:
    import: a
  profiles:
    include: mysql
    active: dev, test
    group:
      dev: dev-mysql, dev-zk
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  profiles:
    include: zk
location: k8s

---
test: test
spring:
  config:
    activate:
      on-profile: test
---
spring:
  config:
    activate:
      on-profile: dev-mysql
bb: 222

---
spring:
  config:
    activate:
      on-profile: dev-zk
cc: 333

---
spring:
  config:
    activate:
      on-profile: dev-zk
cc: 333

###