spring:
  application:
    name: example4springboot
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: 871403165
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
